### ISSUE TITLE
Make app work without JS

### ISSUE THREAD

**Issue by marcoow** [simplabs/breethe-client#86]
Currently, the complete application without JS except for the search form. We could make that work without JS as well though relatively easily.

### Search by search term

If we made the search form a `GET` form with `<form method="GET" action="/search">`, if the browser has JS switched off (or the app has not started so the `onsubmit` handler is not attached yet), that form would submit as e.g. `/search?search-term=munich` which we could simply redirect to `/search/munich` in the SSR server. `/search/munich` is already handled by the SSR server so searching by search term without JS enabled works 🚀 

### Search by coordinates

Without JS, we cannot get the users's coordinates in the browser. We can however, guess their rough coordinates based on their IP on the server side. So making searching by coordinates work without JS could simply work by making the current _"Show nearby locations"_ a link to e.g. `/search-by-coordinates` (that is handled by the app in the browsers via `onclick` once the app has started). When the SSR server sees a request to that path, it could simply get the user's coordinates based on their IP and redirect to e.g. `/search/23.3,45.5` which is already handled by the SSR server. Thus, searching for nearby locations would work without JS as well 🚀

**Comment by jorgelainfiesta** [comment]
I'm reviewing the libraries to get the coordinates out of the user IP. I'm not familiar with the node environment but I've found that https://github.com/bluesmoon/node-geoip seems to be quite popular and is fully written in javascript. However, it uses around 60MB RAM to store the database it uses to map IPs to locations. 

An alternative would be to use https://www.npmjs.com/package/geoip-ultralight, which only provides info about the country, not cities. It only uses 2MB of RAM though.

**Comment by jorgelainfiesta** [comment]
I think `geoip-lite` can provide a much better user experience. I'm preparing the PR using this library.

**Comment by marcoow** [comment]
Is RAM usage actually an issue?
